package dk.magenta.bitmagasinet;

public class Constants {

	public static final String LOCAL_CONFIGURATION_FOLDER = "/Program Files/BitMagGUI/";
	
	public static final String REPOCONF_FOLDER = "repoConf";
	public static final String REPOFILE_EXT = ".conf";
	public static final String CHECKSUMFILE_PREFIX = "ChecksumCheckResult-";
	public static final String CHECKSUMFILE_EXT = ".txt";
	public static final String HEADERFILE_PREFIX = "Header-";
	public static final String HEADERFILE_EXT = ".txt";
	
	public static final String DO_NOT_EDIT_FILE = "AUTOGENERATED - DO NOT EDIT!";
	
}
