package dk.magenta.bitmagasinet.gui;

public class Constants {

	public static final String LOCAL_CONFIGURATION_FOLDER = "BitMagGUI";
	
	public static final String REPOCONF_FOLDER = "repoConf";
	public static final String REPOFILE_EXT = ".conf";
	public static final String CHECKSUMFILE_PREFIX = "ChecksumCheckResult-";
	public static final String CHECKSUMFILE_EXT = ".txt";
	public static final String HEADERFILE_PREFIX = "Header-";
	public static final String HEADERFILE_EXT = ".txt";
	
	public static final String DO_NOT_EDIT_FILE = "AUTOGENERATED - DO NOT EDIT!";
	public static final String CHECKSUM_MATCH_TRUE = "Ja";
	public static final String CHECKSUM_MATCH_FALSE = "Nej";

	// Used to sort results
	public static final String FILENAME = "Filnavn";
	public static final String MATCH = "Stemmer";
	public static final String LOCAL_CHECKSUM = "Lokal kontrolsum";
	public static final String REMOTE_CHECKSUM = "Nedhentet kontrolsum";
}
